--
-- Bloque 3 — ORDER BY
--
-- 11. Artistas ordenados alfabéticamente
--
-- Lista los artistas ordenados por Name en orden ascendente.
--
-- ⸻
--
-- 12. Facturas ordenadas por monto
--
-- Muestra las facturas ordenadas por Total descendente.
--
-- ⸻
--
-- 13. Tracks ordenados por duración y nombre
--
-- Ordena las pistas primero por Milliseconds (ASC), luego por Name (ASC).
