-- Bloque 6 — Comprensión de llaves y relaciones
--
-- 23. Identificar Primary Keys
--
-- Devuelve la lista de columnas que sean Primary Key dentro de la tabla Track.
--
-- (Tip: usa SHOW CREATE TABLE Track o revisa información del diccionario.)
--
-- ⸻
--
-- 24. Identificar Foreign Keys
--
-- Identifica las llaves foráneas de la tabla InvoiceLine.
--
-- (Tip: pista — apunta a Invoice y Track.)
--
-- ⸻
--
-- 25. Relación N:N
--
-- Describe la relación entre Playlist y Track indicando qué tabla intermedia se usa.
